{% set name = "ptvsd" %}
{% set version = "4.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 4ccb23ce84601b6410e0c6b9219229fcf125b47ac55e0fce52ac3a24953e5c52

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python

test:
  imports:
    - ptvsd

about:
  home: https://github.com/Microsoft/ptvsd/
  license: MIT
  license_file: LICENSE
  summary: 'Python debugger package for use with Visual Studio and Visual Studio Code'

extra:
  recipe-maintainers:
    - int19h
    - karthiknadig
    - dhirschfeld
    - rzillman
