travis:
  secure:
    BINSTAR_TOKEN: fR2RroObNFeq3xrHq69RM5d4aKdnEKxVzX/EsF7uu4bDvvuhNwyufJPyUeIT9U1ipGqQq3iQR+ZSdGQyaGpcZNx6MGO2Ql+HTVgCS9ccswrRUuNMI2r8bAiiljz6RCir6MGBTBZ1fw27Cos9vNnTeUXknsplF3xF97ccA4NchCZS7/Sx8drVugS1xaSRHn5hiSdq016zljtZEtRgRgUvS2MX6GN3ejlEbybDd7PaIOJJXMtjBNdECrqV7y3/ZIRL99vNIecf4liLMhUJkIxLopQgD8jaZ61R6d1EPbz/97ahrB3/UeWfzi5WdadM3m9u3cqSzsKy0eJ2ZcNvsA+q/5Wf88OU4KgNppPB2wmbM61z622oxiRRG0k8TLr1l0lZ6wkpiimDuOUB1KG24VR9QQD/OPUKvZTX6DccrjpGwPUlvyrlxw/5Y2d5hItWgFysP5LFyt1bjxczh8UaxUifnZHZII9pmi5L5kouIdvYIusHcl3UZbvN37iz6U/hr+NB9aSd10EcTItwnYxiISRG+Zu5T3wgvarKCPkNo8lajQ0Dmi8QyfPKYX76JNd/uZhCQaikqaG+A9w/OMaEsGKlV/aZsas6hRKEarYDaZJ98tmSVPxV1tm0J6Cop5ZwiYT+2jRv4Be8q3N82hBaTDTgQ3BLnJX6z2jC4YolYUW5BZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
